# Generated by Django 5.2.5 on 2025-09-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summery',
            field=models.TextField(blank=True, null=True),
        ),
    ]
