# Generated by Django 5.2.6 on 2025-09-06 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('about', models.TextField()),
                ('position', models.CharField(choices=[('Team Leader', 'TL'), ('Project Manager', 'PM'), ('Software Engineer', 'SE')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
